import Head from "next/head";
import styles from "../styles/Home.module.css";
import React from "react";

export default function Home() {
  const videoRef = React.useRef();
  const [data, setData] = React.useState(null);
  const [isError, setError] = React.useState(false);
  const [isLoading, setLoading] = React.useState(false);
  const [videourl, setVideourl] = React.useState("");
  const [videoLoading, setVideoLoading] = React.useState(false);

  React.useEffect(() => {
    videoRef.current?.load();
  }, [videourl]);

  React.useEffect(() => {
    console.log("fetching");
    fetch(
      `https://mahad-al-tafsir.herokuapp.com/getYT?id=9Vj8tSVrabk&key=AIzaSyD2ZCJfeVdMeutMVNcq_IXrWPI37_Kx6HM`
    )
      .then((res) => res.json())
      .then((data) => {
        setData(data);
        setLoading(false);
        if (data.data[0].url) {
          setVideourl(data.data[0].url);
        }
      })
      .catch((error) => {
        console.log(error);
        setLoading(false);
      });
  }, []);
  if (isError) return <div>failed to load video</div>;

  console.log(videourl);
  return (
    <div className={styles.container}>
      <Head>
        <title>Video 2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLoading ? (
        <div>Loading...</div>
      ) : (
        <video
          ref={videoRef}
          controls
          controlsList="nodownload"
          key={videourl}
          autoPlay={false}
          width="640"
          onLoadStart={() => console.log("video loading started")}
        >
          <source src={videourl} type="video/mp4" />
          Sorry, your browser doesn't support embedded videos.
        </video>
      )}
    </div>
  );
}
